// Mocks generated by Mockito 5.0.15 from annotations
// in tvshow/test/presentation/bloc/check_watchlist_tv_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tvshow/domain/repositories/tv_repository.dart' as _i2;
import 'package:tvshow/domain/usecase/get_watchlist_status_tv.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeTvRepository_0 extends _i1.Fake implements _i2.TvRepository {}

/// A class which mocks [GetWatchlistStatusTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistStatusTv extends _i1.Mock
    implements _i3.GetWatchlistStatusTv {
  MockGetWatchlistStatusTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvRepository_0()) as _i2.TvRepository);
  @override
  _i4.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  String toString() => super.toString();
}
